# Generated by Django 5.0.4 on 2024-05-10 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_alter_review_review_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 10, 20, 8, 58, 346040, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
