# Generated by Django 5.0.4 on 2024-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_alter_review_review_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
