# Generated by Django 5.0.4 on 2024-05-10 20:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_alter_review_review_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_create_date",
            field=models.DateTimeField(
                auto_now_add=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2024, 5, 10),
                        message="Data de Avaliação deve ser maior ou igual a data de hoje.",
                    )
                ],
            ),
        ),
    ]
