# Generated by Django 5.0.4 on 2024-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="nominated_oscar",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
