# Generated by Django 5.0.4 on 2024-05-05 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0002_actor_nominated_oscar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="nominated_oscar",
        ),
    ]
