# Generated by Django 5.0.4 on 2024-05-10 19:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0003_remove_actor_nominated_oscar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="birthday",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2024, 5, 10),
                        message="Data de Nascimento deve ser menor ou igual a data de hoje.",
                    )
                ],
            ),
        ),
    ]
