# Generated by Django 5.0.4 on 2024-05-05 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_nominated_oscar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="nominated_oscar",
        ),
    ]
