# Generated by Django 5.0.4 on 2024-05-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0001_initial"),
        ("movies", "0003_remove_movie_nominated_oscar"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="awards",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="awards",
                to="awards.award",
            ),
        ),
    ]
