# Generated by Django 5.0.4 on 2024-05-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0001_initial"),
        ("movies", "0004_movie_awards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="awards",
        ),
        migrations.AddField(
            model_name="movie",
            name="awards",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="awards", to="awards.award"
            ),
        ),
    ]
