# Generated by Django 5.0.4 on 2024-05-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0001_initial"),
        ("movies", "0005_remove_movie_awards_movie_awards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="awards",
            field=models.ManyToManyField(related_name="awards", to="awards.award"),
        ),
    ]
